// After adding an emoji here, run tools/build_icons.py: sprite.js only holds the icons this table names.

const ICONS = {
  "🍞": ["lu-croissant", "orange"],
  "🪵": ["mh-log", "brown"],
  "🪨": ["lu-stone", "gray"],
  "⛏": ["lu-pickaxe", "blue"],
  "🌿": ["lu-leaf", "green"],
  "🏺": ["lu-amphora", "orange"],
  "📜": ["lu-scroll-text", "yellow"],
  "🧪": ["lu-flask-round", "pink"],
  "🥪": ["lu-sandwich", "orange"],
  "🥈": ["ra-gold-bar", "teal"],
  "💎": ["ra-crystal-cluster", "purple"],
  "🔧": ["lu-wrench", "gray"],
  "⏫": ["lu-circle-arrow-up", "currentColor"],
  "♻": ["lu-recycle", "green"],
  "🛡": ["lu-shield", "blue"],
  "🪖": ["lu-chess-knight", "blue"],
  "🏹": ["lu-bow-arrow", "green"],
  "🔥": ["lu-flame", "orange"],
  "✚": ["lu-cross", "yellow"],
  "🏕": ["lu-flame-kindling", "orange"],
  "🛖": ["lu-tent", "brown"],
  "🏠": ["lu-house", "brown"],
  "🌾": ["lu-wheat", "yellow"],
  "🪓": ["lu-axe", "brown"],
  "⛰": ["lu-mountain", "gray"],
  "⚒": ["lu-anvil", "gray"],
  "⏳": ["lu-hourglass", "gray"],
  "🩹": ["lu-bandage", "pink"],
  "📚": ["lu-library-big", "purple"],
  "🌲": ["lu-tree-pine", "green"],
  "🏰": ["lu-castle", "brown"],
  "🏛": ["lu-landmark", "yellow"],
  "🍖": ["lu-ham", "red"],
  "🎣": ["lu-fishing-rod", "blue"],
  "⛪": ["lu-church", "gray"],
  "🦴": ["lu-bone", "ink"],
  "🛝": ["lu-ferris-wheel", "orange"],
  "🛐": ["lu-bell", "yellow"],
  "🎻": ["lu-music", "purple"],
  "🪚": ["lu-hammer", "brown"],
  "🐎": ["ra-horseshoe", "gray"],
  "🍺": ["lu-beer", "orange"],
  "🗻": ["ra-mountains", "brown"],
  "🏔": ["lu-mountain-snow", "gray"],
  "🌊": ["lu-waves", "blue"],
  "🧱": ["lu-brick-wall", "orange"],
  "⚔": ["lu-sword", "ink"],
  "🏞": ["lu-trees", "green"],
  "🪔": ["ra-candle", "yellow"],
  "👹": ["ra-monster-skull", "red"],
  "📕": ["lu-book-marked", "brown"],
  "🤺": ["lu-swords", "ink"],
  "💨": ["lu-wind", "teal"],
  "❤": ["lu-heart", "red"],
  "🛏": ["lu-bed", "blue"],
  "🔒": ["lu-lock", "gray"],
  "😔": ["lu-frown", "blue"],
  "✓": ["lu-check", "currentColor"],
  "✕": ["lu-x", "currentColor"],
  "❯": ["lu-chevron-right", "currentColor"],
  "▸": ["lu-chevron-right", "currentColor"],
  "▶": ["lu-play", "currentColor"],
  "🙋": ["lu-hand", "yellow"],
  "↕": ["lu-maximize-2", "currentColor"],
  "⇳": ["lu-minimize-2", "currentColor"],
  "⏸": ["lu-pause", "currentColor"],
  "🏘": ["lu-tent-tree", "brown"],
  "👥": ["lu-users", "ink"],
  "🧭": ["lu-compass", "teal"],
  "⚙": ["lu-settings", "currentColor"],
  "📖": ["lu-book-open-text", "ink"],
  "🎯": ["lu-locate-fixed", "currentColor"],
  "📋": ["lu-clipboard-copy", "currentColor"],
  "💾": ["lu-download", "currentColor"],
  "📂": ["lu-folder-open", "currentColor"],
  "📥": ["lu-log-in", "currentColor"],
  "📲": ["lu-smartphone", "currentColor"],
  "⛶": ["lu-maximize", "currentColor"],
  "🦺": ["lu-shirt", "brown"],
  "📦": ["lu-package", "brown"],
  "🍽": ["lu-utensils-crossed", "orange"],
  "🪦": ["ra-tombstone", "gray"],
  "💔": ["lu-heart-crack", "red"],
  "🏆": ["lu-trophy", "yellow"],
  "⭐": ["lu-star", "yellow"],
  "🔨": ["lu-hammer", "brown"],
  "👣": ["lu-footprints", "gray"],
  "😄": ["lu-laugh", "green"],
  "🙂": ["lu-smile", "teal"],
  "😐": ["lu-meh", "gray"],
  "😠": ["lu-angry", "red"],
  "💬": ["lu-message-circle-warning", "red"],
  "🐀": ["lu-rat", "brown"],
  "🟢": ["ra-gloop", "green"],
  "💀": ["lu-skull", "ink"],
  "🦇": ["ra-batwings", "purple"],
  "🕯": ["ra-hood", "purple"],
  "🧟": ["ra-monster-skull", "green"],
  "🌱": ["ra-thorny-vine", "green"],
  "☠": ["ra-death-skull", "ink"],
  "🌳": ["ra-dead-tree", "brown"],
  "👁": ["ra-eye-monster", "red"],
  "👀": ["lu-eye", "blue"],
  "🎲": ["lu-dices", "ink"],
  "🐺": ["ra-wolf-head", "gray"],
  "🕷": ["ra-spider-face", "purple"],
  "👻": ["lu-ghost", "teal"],
  "🌀": ["lu-loader-pinwheel", "brown"],
  "🛒": ["lu-pickaxe", "gray"],
  "🎄": ["lu-trees", "green"],
  "⛩": ["ra-ankh", "teal"],
  "🚪": ["lu-door-open", "brown"],
  "💰": ["lu-coins", "yellow"],
  "⛲": ["ra-ankh", "teal"],
  "❔": ["lu-circle-question-mark", "purple"],
  "🪜": ["lu-door-stairwell", "gray"],
  "🌬": ["mh-windmill", "brown"], "👑": ["lu-crown", "yellow"],
  "👊": ["lu-hand-fist", "red"], "✨": ["lu-sparkles", "yellow"], "🗡": ["ra-plain-dagger", "red"], "💍": ["lu-gem", "pink"],
  "🔦": ["ra-torch", "orange"], "🛣": ["lu-route", "yellow"],
};

const ic = (e) => {
  const [id, hue] = ICONS[e];
  const color = hue === "currentColor" ? hue : hue === "ink" ? "var(--ink)" : `var(--c-${hue})`;
  return `<svg class="i" style="color:${color}" aria-hidden="true"><use href="#${id}"/></svg>`;
};

// Any emoji, with or without its trailing variation selector. Longest first so nothing
// shorter eats the start of a longer one.
const ICON_RE = new RegExp(`(${Object.keys(ICONS).sort((a, b) => b.length - a.length)
  .map((k) => k.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|")})\uFE0F?`, "gu");

// Only text between tags is touched; attributes (alt, title) keep their emoji.
const iconize = (html) => String(html).split(/(<[^>]*>)/).map((part) =>
  part[0] === "<" ? part : part.replace(ICON_RE, (_, e) => ic(e))).join("");

if (typeof SPRITE === "string") document.body.insertAdjacentHTML("afterbegin", SPRITE);
