#!/usr/bin/env python3
"""
Writes js/ds/sprite.js: one hidden inline SVG of <symbol>s holding just the icons that
js/ds/icons.js names, so the game ships a few dozen icons instead of two icon sets.

Run from the project root:  python3 tools/build_icons.py
Downloads sources once into tools/.cache/.

RPG Awesome ships only a webfont, so its glyphs come out of fonts/rpgawesome-webfont.svg: each
<glyph> is a path in font units (1024/em, y-up, baseline at 0, ascent 960), so it gets a
y-flip. Lucide ships real SVGs drawn in currentColor, which the page tints per icon.
"""
import io, json, re, sys, tarfile, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "tools" / ".cache"
TABLE = ROOT / "js/ds/icons.js"
OUT = ROOT / "js/ds/sprite.js"

RA_FONT = "https://raw.githubusercontent.com/nagoshiashumari/Rpg-Awesome/master/fonts/rpgawesome-webfont.svg"
RA_CSS = "https://raw.githubusercontent.com/nagoshiashumari/Rpg-Awesome/master/css/rpg-awesome.css"
LUCIDE_NPM = "https://registry.npmjs.org/lucide-static"


def fetch(url: str, name: str) -> bytes:
    CACHE.mkdir(parents=True, exist_ok=True)
    p = CACHE / name
    if not p.exists():
        with urllib.request.urlopen(url, timeout=60) as r:
            p.write_bytes(r.read())
    return p.read_bytes()


def rpg_awesome(wanted: set[str]) -> dict[str, str]:
    font = fetch(RA_FONT, "ra-font.svg").decode("utf-8", "replace")
    css = fetch(RA_CSS, "ra.css").decode("utf-8", "replace")
    # The CSS carries the names; the font carries the paths. Join them on the codepoint.
    names = {ord(ch): n for n, ch in
             re.findall(r'\.ra-([a-z0-9-]+):before\s*\{\s*content:\s*"(.)"', css)}
    out = {}
    for cp_hex, attrs in re.findall(r'<glyph unicode="&#x([0-9a-fA-F]+);"([^/]*)/>', font):
        name = names.get(int(cp_hex, 16))
        d = re.search(r'\sd="([^"]+)"', attrs)
        if name and d and "ra-" + name in wanted:
            out["ra-" + name] = (f'<symbol id="ra-{name}" viewBox="0 0 1024 1024">'
                                 f'<path transform="translate(0,960) scale(1,-1)" d="{d.group(1)}" fill="currentColor"/></symbol>')
    return out


def lucide(wanted: set[str]) -> dict[str, str]:
    meta = json.loads(fetch(LUCIDE_NPM, "lucide-registry.json"))
    version = meta["dist-tags"]["latest"]
    tgz = fetch(meta["versions"][version]["dist"]["tarball"], "lucide-static-%s.tgz" % version)
    out = {}
    with tarfile.open(fileobj=io.BytesIO(tgz)) as tar:
        for m in tar.getmembers():
            if not (m.name.startswith("package/icons/") and m.name.endswith(".svg")):
                continue
            key = "lu-" + Path(m.name).stem
            if key not in wanted:
                continue
            svg = tar.extractfile(m).read().decode()
            body = re.sub(r"<!--.*?-->", "", re.search(r"<svg[^>]*>(.*)</svg>", svg, re.S).group(1))
            body = re.sub(r"\s+", " ", body).strip()
            out[key] = (f'<symbol id="{key}" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
                        f'stroke-width="2" stroke-linecap="round" stroke-linejoin="round">{body}</symbol>')
    return out


# Drawn here in Lucide's stroke style for what neither set has (mh- ids).
CUSTOM = {
    # a cut log lying on its side: ring-marked end face, bark body
    "mh-log": '<ellipse cx="6" cy="12" rx="3" ry="6"/><circle cx="6" cy="12" r="1.2"/>'
              '<path d="M6 6h12a3 6 0 0 1 0 12H6"/><path d="M11 9.5h4M13 14.5h3"/>',
}


def custom(wanted: set[str]) -> dict[str, str]:
    return {k: (f'<symbol id="{k}" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
                f'stroke-width="2" stroke-linecap="round" stroke-linejoin="round">{v}</symbol>')
            for k, v in CUSTOM.items() if k in wanted}


if __name__ == "__main__":
    wanted = set(re.findall(r'"((?:lu|ra|mh)-[a-z0-9-]+)"', TABLE.read_text()))
    found = {**lucide(wanted), **rpg_awesome(wanted), **custom(wanted)}
    missing = sorted(wanted - found.keys())
    if missing:
        sys.exit("not in either set: " + ", ".join(missing))
    sprite = ('<svg xmlns="http://www.w3.org/2000/svg" style="display:none">'
              + "".join(found[k] for k in sorted(found)) + "</svg>")
    OUT.write_text("// Generated by tools/build_icons.py from js/ds/icons.js. Do not edit.\n"
                   "// Lucide (ISC) and RPG Awesome (SIL OFL 1.1); see ICON-LICENSES.md.\n"
                   f"const SPRITE = {json.dumps(sprite)};\n")
    print(f"{len(found)} icons -> {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")
